services:

  postgresql:
    container_name: api-postgresql
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_USER=api
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - api-postgresql:/var/lib/postgresql/data
    networks:
      - api-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - postgresql
    environment:
      - ENVIRONMENT=development
      - POSTGRESQL_URL=jdbc:postgresql://postgresql:5432/api
      - POSTGRESQL_USERNAME=api
      - POSTGRESQL_PASSWORD=api
      - JWT_SECRET=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    networks:
      - api-network

volumes:
  api-postgresql:
    driver: local

networks:
  api-network:
    driver: bridge
